### ISSUE TITLE
Flatpak release

### ISSUE THREAD

**Issue by felix920506** [FoldingAtHome/fah-client-bastet#107]
Enhancement: Would like to see official Flatpak release. This would make life a lot easier for Linux users.

Flatpaks can be installed on any Linux distro that supports it without requiring apps to be specifically packaged for each individual distro. Flatpaks are also the only way to install apps on the Steam Deck without the use of dev mode (According to info found online).

**Comment by marcosfrm** [comment]
It does not appear trivial run `fah-client` in the background:

https://github.com/flatpak/flatpak/issues/118

Here is a crude attempt to only build `fah-client` using Freedesktop SDK:

```yml
# sudo apt install flatpak flatpak-builder
# https://flatpak.org/setup/Debian
# sudo flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
# sudo flatpak install flathub org.freedesktop.Platform//22.08 org.freedesktop.Sdk//22.08
# mkdir -p build-dir
# flatpak-builder --force-clean build-dir wip.yml

app-id: org.foldingathome.fah-client
runtime: org.freedesktop.Platform
runtime-version: '22.08'
sdk: org.freedesktop.Sdk
command: fah-client
finish-args:
  - --share=network
  - --device=dri
modules:
  - name: scons
    buildsystem: simple
    cleanup: ['*']
    sources:
      - type: archive
        url: https://sourceforge.net/projects/scons/files/scons/4.5.2/SCons-4.5.2.tar.gz
        sha256: ce26aac95d350a79a4192196b0beac3cb24f4ccabce0123eb28d3370f576f072
    build-commands:
      - pip3 install --no-index --no-build-isolation --prefix=/app .

  - name: cbang
    buildsystem: simple
    cleanup: ['*']
    sources:
      - type: archive
        url: https://github.com/CauldronDevelopmentLLC/cbang/archive/refs/tags/bastet-v8.2.2.tar.gz
        sha256: 43a5b99e056b37ca6a2185821e806e5be53e33b26d2e03344d053f2ce32468a3
    build-commands:
      - scons
      - mkdir -p /app/tmp/cbang
      - cp -a . /app/tmp/cbang

  - name: fah-client
    buildsystem: simple
    cleanup: ['/tmp']
    build-options:
      env:
        CBANG_HOME: /app/tmp/cbang
    sources:
      - type: archive
        url: https://github.com/FoldingAtHome/fah-client-bastet/archive/refs/tags/v8.2.2.tar.gz
        sha256: 43e329553f2c9223b6eefb316020623676e8becf2be8ea1e8132aaacb877845a
    build-commands:
      - scons
      - install -p -t /app/bin fah-client
```

https://docs.flatpak.org/en/latest/index.html
